### ISSUE TITLE
Quest for melter not working even though I made it!

### ISSUE THREAD

**Issue by Boogon** [SmashingMods/Volcano-Block#101]

**Comment by al132mc** [comment]
Sorry for the late response, could you please take a screenshot of your quest screen?

**Comment by tramper15** [comment]
![image](https://user-images.githubusercontent.com/19995909/75600660-94116f00-5a77-11ea-94b0-a1fa82c80660.png)
having same issue

**Comment by al132mc** [comment]
If you look carefully, you'll notice that the melter quest requires the quest for ember crystals to also be fully completed, which's it's not because it doesn't have a green checkmark next to it.
