### ISSUE TITLE
Server isnt opening

### ISSUE THREAD

**Issue by Sardonyx78** [SmashingMods/Volcano-Block#102]
The cmd just pops and closes
yes I installed the forge server

**Comment by al132mc** [comment]
how are you trying to run the server? Please use the ServerStart script appropriate for your operating system. (.sh for linux, .bat for windows)

**Comment by Urdraconic** [comment]
I know this is old but I figured I shouldn't make a post on the exact same issue, wanted to play with some friends, I install the forge server, double click the serverstart.bat, (I'm on windows) and it shows up for half a second before closing, all that happens is it generates a log file, that just says that it detected the settings.cfg, but never launched. I feel like maybe there is something I am missing but I tried figuring it out for like an hour and have no clue what else to do now.

**Comment by al132mc** [comment]
Sorry for the late response. Try re-installing *without* installing Forge. ServerStart.bat will install forge for you.

**Comment by shart** [comment]
error using the .sh file. 

`./ServerStart.sh: 36: ./ServerStart.sh: Syntax error: "(" unexpected (expecting "then")
`

**Comment by shart** [comment]
Never Mind, no sh. needs to be run with bash. I read the script.
