### ISSUE TITLE
Gelatin powder recipe not working with Structural Crafting

### ISSUE THREAD

**Issue by SuddenTurmoil** [SmashingMods/Volcano-Block#105]
The Structural Crafter can make gelatin powder when rabbit pelts are used but cannot make it when dusty bones or bones (regular, vanilla bones made with the chemical combiner) are used. The recipe using bones works in a vanilla or compact crafting table. For the 20k Klingon gelo though, automation is necessary.

**Comment by al132mc** [comment]
In v1.0.31 i've decided to add an in-world crafting recipe as an alternative for gelatin powder. I'm not sure why it won't work with the structured crafter, but hopefully this is adequate...

**Comment by SuddenTurmoil** [comment]
The in world recipe doesn't work with Atum 2 dusty bones. The update did not fix the Structural Crafting recipe (I know it wasn't supposed to, just wanted to confirm that it still isn't working).
