### ISSUE TITLE
Game crash in atum dimension when soulus summoner spawn

### ISSUE THREAD

**Issue by immortalmice** [SmashingMods/Volcano-Block#106]
I got in to atum dimension, and there's some soulus summoner in structures.
When I got close to them, crash happend.
It make me almost impossible to stay in atum dimension and finish the quest.

I read the crash report, here's some infomation

> Description: Ticking block entity

>java.lang.NullPointerException: Ticking block entity
>	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.spawn(SummonerTileEntity.java:494)
>	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.func_73660_a(SummonerTileEntity.java:334)
>	at net.minecraft.world.World.func_72939_s(World.java:1838)
>	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
>	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>	at java.lang.Thread.run(Thread.java:745)

I couldn't find out what may related to this crash with soulus summoner spawning.
It's just simple, I got close to the summoner, then game crash, everytime.
So if you need other infomation in crash report or something I may have, please tell me. I'll give it to you.

I updated the pack version from 1.0.32 to 1.0.34, crash still happened with same reason.
Soulus version is 4.3.3-f3404c1.
Atum version is 2.0.16.

By the way, the summoner I made in the overworld work fine, no crash no something weird.

thx.

**Comment by immortalmice** [comment]
OK, I go to read the source code of soulus.
And I find the problem.
In the line 494 of yuudaari.soulus.common.block.summoner.SummonerTileEntity.java, spawn function.

> final String[] spawnNames = CONFIG_ESSENCES.get(essenceType).spawnNames;

It trying to get the name of the essence.
So I go to read yuudaari.soulus.common.config.essence.ConfigEssences where CONFIG_ESSENCES come from.

In line 85

> return essences.stream().filter(config -> config.essence.equalsIgnoreCase(type)).findFirst().orElse(null);

So the problem happend when it can't find matched data, so it will return null.
But at line 494 of SummonerTileEntity.java, it will try to get "spawnNames" property in a null pointer.
Then caused NullPointerException and game crash.

Check the return value of "get" function first before get spawnNames property will be much better. 

I will also create a issue in soulus to report this problem.

thx.

**Comment by emik101** [comment]
add the following to the end of the essences.json file in the soulus config...

`,
		{
			"essence": "atum:mummy",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:assassin",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:barbarian",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:bonestorm",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:brigand",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:forsaken",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:heart_of_ra",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:nomad",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:pharaoh",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:stoneguard",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:stonewarden",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:sunspeaker",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:tarantula",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:warlord",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:wraith",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:camel",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:scarab",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:desert_rabbit",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:desert_wolf",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},
		{
			"essence": "atum:tefnuts_call",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		}`

**Comment by emik101** [comment]
the comma should be right after the } in the magma cube entry like so...
{
			"essence": "minecraft:magma_cube",
			"name": null,
			"spawn_names": null,
			"colors": null,
			"bones": null,
			"soulbook_quantity": 16,
			"spawns": null,
			"loot": null
		},<------ this comma begins the copypasta

**Comment by immortalmice** [comment]
@emik101 
Thanks for your data, I used it to expand the array in JSON file, and game won't crash now.

**Comment by emik101** [comment]
don't forget to check creatures#no_creatures#no_drops.json 
,
			"atum:*": {
				"spawn_chance": 1.0,
				"drops": {
					"summoned": {
						"has_xp": true,
						"whitelisted_drops": [
							"*"
						],
						"blacklisted_drops": []
					}
				}
this must be in the file like this or regular mob spawning will not happen

**Comment by FelixLouis** [comment]
Why is this closed? The bug is still here.
