### ISSUE TITLE
Can't automatically placing fluids on flowing fluid (non-source block)

### ISSUE THREAD

**Issue by Animaly0** [SmashingMods/Volcano-Block#107]
I can't place with "floppers", nor with "fluid world exporters" water on a flowing water block.
I have the same issue on version 1.0.30 and 1.0.34 of the modpack

![2019-12-08_02 09 53](https://user-images.githubusercontent.com/52257781/70382668-dedf8700-195f-11ea-8213-697ac8d2a4ca.png)

**Comment by al132mc** [comment]
Not really a pack bug.. just intended behavior i'd imagine
