### ISSUE TITLE
Crash while generating superflat world

### ISSUE THREAD

**Issue by lolamchan** [SmashingMods/Volcano-Block#113]
i used this preset
3;minecraft:bedrock,59*minecraft:lava;1;hell;biome_1
someone help me make a preset
[crashed 17:3.txt](https://github.com/al132mc/Volcano-Block/files/4341066/crashed.17.3.txt)

**Comment by MasterEnderman** [comment]
The pack currently uses Topography to generate the world. Any other method probably results in a crash. I'll try to replace it and use another method to create new worlds.
