### ISSUE TITLE
Diamond tree drop table issue

### ISSUE THREAD

**Issue by 3LilyFarmer** [SmashingMods/Volcano-Block#114]
I don't know what causes it. But once in a while when I harvest my diamond tree I'll get only weakened diamond and once I got nothing at all. And when I check the diamond leaves on JEI. It'll show a blank spot on the diamond and one time both spots, the diamond and weakened diamond, came up empty and when that happens you will get no drop for harvesting diamond tree. Ideally, I'm hoping that in a future version there will be at least one more recipe for creating more diamond tree sapling ideally with diamond wood or leaves; or fixing the diamond tree drop glitch, whichever is easier.

**Comment by 3LilyFarmer** [comment]
After some more testing and checking out the calculator github discussion. I've figured out that this is a calculator mod issue with sickle leaves drop. It seems that there is a way to change the loot table for the diamond leaves and pear leaves so that the leaves drop nothing or a full stack of loot depending on a certain action. The drop rate of diamond leaves and pear leaves is unchanged, but it'll drop a lot or a little item when the leaf block generates a drop action if you perform this glitch.

**Comment by MasterEnderman** [comment]
After checking out the problem myself. I found out that the diamond leave has 4 growth stages
- FRESH
- GROWING
- READY (yields a weakened diamond)
- MATURE (yields a flawless and a weakened diamond)
as far as I can see the only way to "see" the growth stage is to check the F3 menu.
FYI: If you click a leave with a Sickle it resets it's growth stage back to "FRESH" so you lose your progress if you just click it constantly.
