### ISSUE TITLE
I don't think these are supposed to stack...

### ISSUE THREAD

**Issue by AnAwesomGuy** [SmashingMods/Volcano-Block#125]
https://user-images.githubusercontent.com/79700396/112720222-70fffb80-8ed3-11eb-8e1c-51738f03282e.mp4

**Comment by al132mc** [comment]
As long as they have the same exact NBT data (which they should if the game lets them stack) then it shouldn't be a problem.

**Comment by AnAwesomGuy** [comment]
oh well, I got them by dying and how does that work?
