### ISSUE TITLE
huh?

### ISSUE THREAD

**Issue by AnAwesomGuy** [SmashingMods/Volcano-Block#126]
https://user-images.githubusercontent.com/79700396/113480144-ee41e800-9460-11eb-90cf-617051d36397.mp4

**Comment by AnAwesomGuy** [comment]
If you don't get it, says "no tool". P.S. pleeeease make sugarcane drop more from grass. I'm having trouble getting it.

**Comment by OniyaMCD** [comment]
The 'no tool' is because your target is the blood splatter.  Look into EvilCraft for how to harvest that.
