### ISSUE TITLE
recipe bug

### ISSUE THREAD

**Issue by zen-zen-zen** [SmashingMods/Volcano-Block#134]
i cant even get glue when trow sugar and paper in water 1 block its dont consume water and transform

**Comment by OniyaMCD** [comment]
It's not sugar and paper.  It should be sugar and bone meal.

**Comment by MasterEnderman** [comment]
It is sugar and bone meal:
```
FluidToItem.transform(<soulus:glue>, <liquid:water>, [<ore:bonemeal>,<minecraft:sugar>], true);
```
