### ISSUE TITLE
Lily pads unobtainable

### ISSUE THREAD

**Issue by rweidman** [SmashingMods/Volcano-Block#142]
Lily pads are needed for obsidian skull recipe, but lily pads can only be obtained via botania, which is gated behind the blood infuser (which requires an obsidian skull).  Fishing also does not seem to drop lily pads (though maybe I am just unlucky).

**Comment by OniyaMCD** [comment]
In previous versions of the pack, there was a lava lily, available through Unique Crops, that could be used in the recipe as well.

**Comment by rweidman** [comment]
The lava lily is still there, and is required for the obsidian skull recipe, however it needs a vanilla lily pad to craft.
