### ISSUE TITLE
Modular Modem Sender Module game stage

### ISSUE THREAD

**Issue by SuddenTurmoil** [SmashingMods/Volcano-Block#144]
The Sender Module, which lets the Modular Modem push items into other blocks or inventories, requires an arrow to craft. Arrows are gated behind Solous summoning. This makes the modem able to pull items in as soon as you get iron, but unable to push them until mid game.

**Comment by MasterEnderman** [comment]
any idea what would be a good replacement for it?

**Comment by SuddenTurmoil** [comment]
Inspiration pipe? Make is useful for something?
