### ISSUE TITLE
Modular Modem Vacuum Module game stage

### ISSUE THREAD

**Issue by SuddenTurmoil** [SmashingMods/Volcano-Block#146]
The Vacuum Module allows the Modular Modem to pick up items nearby. To craft it requires an eye of ender. Its functionality can be replicated with mini gravity blocks and hoppers early on so gating this behind Soulus mob summoning seems unnecessary. I would suggest replacing the eye of ender in the crafting recipe with a mini gravity block to both integrate it with other mods and allow earlier access.

**Comment by MasterEnderman** [comment]
#145
