### ISSUE TITLE
Instabilis seeds not growing

### ISSUE THREAD

**Issue by Catalinutsz** [SmashingMods/Volcano-Block#152]
I tried to grow the plant for detcord, but it does`t grow. I gave the plants light and bonemeal but nothing. Any ideas on how to solve this?

**Comment by OniyaMCD** [comment]
Make sure that you have arranged five instabilis plants in a plus sign (+),  As the book says, they must be surrounded by their own kind to grow.

**Comment by Catalinutsz** [comment]
It works like that. Thank you so much!
