### ISSUE TITLE
Repair paste bug

### ISSUE THREAD

**Issue by Salaru** [SmashingMods/Volcano-Block#162]
I had 3 repair paste in my inventory to speed up repairing my Fortune III pick, and when one broke it deleted my pick and auto-replaced it with a damaged repairing paste. Might wanna switch to regular inventory tweaks? The one being used seems buggy... 
And the repair pastes should be breaking the other ones in the inventory before the one in the off hand anyways... Have to turn off auto-refill. 
And yes. I tried it again to make sure. 
Recap. 
Using more than one repairing paste to repair anything to the point that a repairing paste breaks during repair will replace/destroy what's being repaired with an already damaged repair paste.

**Comment by MasterEnderman** [comment]
Sorry to hear you experiencing this bug for yourself. I already reported it to the author with some more bugs I found. 
There should be a fix within the next few days. (I'll release an update shortly after.)
Yes I know that it isn't working as smooth as inventory tweaks (yet), but at least the author still supports his mod. You can always switch to inventory tweaks yourself if you're not happy with the solution I provide for inventory sorting. :)

**Comment by Salaru** [comment]
Yeah I did. But even disabling auto-refill on the glitchy one doesn't guarantee it doesn't auto-refill. It sometimes still does. And I can't remove it because the server won't let me log in if I do. Should be client side and not required like inventory tweaks...
