### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by Chtholly-dev** [SmashingMods/Volcano-Block#164]
For some reason if you die to many times you get teleported over a thousand blocks away from the starting island. The modpack wasn't changed. No mods updated, added or removed. After killing myself with the starting knife to farm a ton of bonemeal when trying to respawn I wake up at y: 5 over a thousand blocks away. To make it even better this happened on a server as well but there I got teleported 3 thousand blocks away from my starting island and woke up near the server spawn. (This happened on the official server).

**Comment by SuddenTurmoil** [comment]
This also happens occasionally when returning from The End. Here is the spot you get dropped.
![image](https://user-images.githubusercontent.com/4281297/196797952-664df87d-b663-4a22-8889-17679047ccfd.png)

**Comment by MasterEnderman** [comment]
I'll probably just delete all the lava around spawn....
