### ISSUE TITLE
Greater Sprite does not drop heart in SMP [Progress Blocker]

### ISSUE THREAD

**Issue by SuddenTurmoil** [SmashingMods/Volcano-Block#166]
When spawning a greater sprite in SP and killing it the heart properly drops. On the server the heart does not drop. Tested with Zorrasteel sword and endsteel sword in both settings. Replicated Coral perk levels, armor,, weapons, and baubles in SP without causing the same outcome.

**Comment by SuddenTurmoil** [comment]
Both SMP and SP areas were FTB Teams claimed.

**Comment by SuddenTurmoil** [comment]
I can get the hearts to drop if I have ID kill the guardian with my sword. It's not elegant, but it is a temporary workaround.

**Comment by SuddenTurmoil** [comment]
Going back over all the quests again I found that ranged weapons will still drop hearts for me, so the prodegytech handbow or Botania Chakram both dropped hearts for me. The Kings Key did not but I suspect that doesn't count as a player kill no matter what.

**Comment by MasterEnderman** [comment]
I moved the implementation of the new drops from CraftTweaker to InControl, did some testing with it and it seems to be much more reliable.
