### ISSUE TITLE
Istabilish seed not growing

### ISSUE THREAD

**Issue by Shanto2003** [SmashingMods/Volcano-Block#172]
I see that even with bonemeal the Istabilish seed is not growing

**Comment by OniyaMCD** [comment]
As per the Unique Crops book, this seed needs to be surrounded by others of its type in order to grow.  The easiest way to do this is to plant five seeds in a + pattern.

**Comment by Shanto2003** [comment]
Normie seeds is a unique crops. Tried putting it next to them and it doesn't work either

**Comment by Shanto2003** [comment]
> As per the Unique Crops book, this seed needs to be surrounded by others of its type in order to grow. The easiest way to do this is to plant five seeds in a + pattern.

Normie seeds is a unique crops. Tried putting it next to them and it doesn't work either

**Comment by OniyaMCD** [comment]
Others **of it's type**.  That is, other Instabilis seeds.  Remember to use the Heavy Shears to harvest it.

**Comment by Shanto2003** [comment]
> Others **of its type**. That is, other Instabilis seeds. Remember to use the Heavy Shears to harvest it.

[https://imgur.com/a/LZcc1Pq](url) I just tried it and it didn't work
