### ISSUE TITLE
Im join in my world, and i see just nothing only dark. When im in any fluid im able to see blocks and etc.

### ISSUE THREAD

**Issue by StasJojo1213** [SmashingMods/Volcano-Block#174]

**Comment by OniyaMCD** [comment]
Make sure your graphics card drivers are up to date.  If they are, start by changing Graphics from 'Fast' to 'Fancy'.  If you've added Optifine, remove it.  If that still doesn't fix it, remove the 'FogTweaker' mod.

**Comment by StasJojo1213** [comment]
> Make sure your graphics card drivers are up to date. If they are, start by changing Graphics from 'Fast' to 'Fancy'. If you've added Optifine, remove it. If that still doesn't fix it, remove the 'FogTweaker' mod.

Thx, it helps.
