### ISSUE TITLE
Instabillis seeds doesn't grow

### ISSUE THREAD

**Issue by Homckach** [SmashingMods/Volcano-Block#175]
Instabillis seeds doesn't grow. I placed it near 9 torches and they still not growing. I used 2 stacks of bonemeal.

**Comment by Homckach** [comment]
Fix it please or say reason why they isnt growing.

**Comment by Timbroglio** [comment]
As per the Unique Crops book, this seed needs to be surrounded by others of its type in order to grow. The easiest way to do this is to plant five seeds in a + pattern.

**Comment by Homckach** [comment]
thank you very much
