### ISSUE TITLE
Volcano block lightning issue

### ISSUE THREAD

**Issue by SrGustavoo10** [SmashingMods/Volcano-Block#178]
Basically when I start a new map, I can walk and die in lava and see my hotbar, but I can't see anything else like blocks, lava, it gets a dark screen

**Comment by SrGustavoo10** [comment]
it works normally on fancy graphics, but when I switch to fast it gets bug

**Comment by OniyaMCD** [comment]
The solutions to this problem include 
1) Switching to fancy graphics (easiest, and the one you've discovered)
2) Updating your graphics card drivers and
3) Removing the FogTweaker mod.
