### ISSUE TITLE
Modpack incompatible with Optifines [Fast Graphics]

### ISSUE THREAD

**Issue by SSAhakan771** [SmashingMods/Volcano-Block#179]
![2022-12-26_19 37 35](https://user-images.githubusercontent.com/121453208/209572540-121e7775-e50c-4d12-a78b-c06e61a7a85c.png)
 
I just downloaded volcano block, I entered the game and the screen was black like this, I deleted the world and opened it again, but it was still black can someone help?

**Comment by OniyaMCD** [comment]
The solutions to this problem include 
1) Switching to fancy graphics (easiest)
2) Updating your graphics card drivers and
3) Removing the FogTweaker mod.

**Comment by SSAhakan771** [comment]
thnks <3
