### ISSUE TITLE
wont let me craft cooble seeds 

### ISSUE THREAD

**Issue by monkeyman123-max** [SmashingMods/Volcano-Block#182]
ive tried everything now and kinda frustrated beacause am trying to make a youtube video and am kinda on a deadline and the game just wont let me craft cooble seed idk why but please get back to me as soon as posible

**Comment by SuddenTurmoil** [comment]
Read the quests and read the Unique Crops guidebooks, they will serve you well (except for the instabilis seed quest, ignore that one's quest text). 
To craft the cobbolnia seed you need a 3x3 (9 total) field of artisia seeds fully grown. You then drop the ingredients into the field of artisia plants and it will craft the cobblonia seed. 
If you look in JEI you will see it uses the Seed Crafting Recipe, with an image of a grown artisia plant on the left. This crafting method is used for most Unique Crops crafting.
Also, the discord is faster for things like this.

**Comment by monkeyman123-max** [comment]
> 

okay thx
