### ISSUE TITLE
Volcano Block Black screen upon joining a server

### ISSUE THREAD

**Issue by utsanslover16** [SmashingMods/Volcano-Block#184]
Hello so me and my boyfriend were trying to play this modpack together and this happened to him while mines looked completely fine. We reloaded the game and it was still doing that. Apparently he could see everything through water and under lava. Reloading chunks and textures didn't work either. If I knew what the problem was maybe we could solve it. His pc specs are in the F3 picture he sent me yesterday. 

![rn_image_picker_lib_temp_c978cada-ef85-4558-9271-2677efa416ec](https://user-images.githubusercontent.com/69633200/215438909-f234e329-16ec-43e9-b83d-3f64f2112c8f.jpg)

**Comment by MasterEnderman** [comment]
https://github.com/SmashingMods/Volcano-Block/issues/179
