### ISSUE TITLE
Darkness on fast graphics 

### ISSUE THREAD

**Issue by gamepee** [SmashingMods/Volcano-Block#185]
![Capture](https://user-images.githubusercontent.com/67324387/229340539-cdef9570-1943-45b8-9c4d-20786708110a.PNG)
I tried doing what one of the issues said "remove fogtweaker" but I can't seem to find that mod in the folder. Are there any other solutions to this?

**Comment by RemagOfficial** [comment]
switch to fancy graphics

**Comment by gamepee** [comment]
> switch to fancy graphics

and without that?

**Comment by MasterEnderman** [comment]
The mod is called `Fog World`, either remove it or switch to `fancy` graphics in optifine.
