### ISSUE TITLE
help instabilis doesnt grow, i tried bone meal

### ISSUE THREAD

**Issue by snowfall2836** [SmashingMods/Volcano-Block#188]
![2023-05-22_23 05 21](https://github.com/SmashingMods/Volcano-Block/assets/134309113/a0fd3935-8393-47c1-b48a-1a3519ecae8c)

**Comment by Gazzoose075** [comment]
надо построить 3х3 и все)

**Comment by Gazzoose075** [comment]
Смотреть за внимание!
https://github.com/SmashingMods/Volcano-Block/issues/189
