### ISSUE TITLE
Растение Instabilis seed БАГ(

### ISSUE THREAD

**Issue by Gazzoose075** [SmashingMods/Volcano-Block#189]
Я не нравится что ошибка далеть в игру и баг, https://youtu.be/L3AfTlyGncM на ютуб смотри 3:38:03 и еще опять 3:44:30
![2023-05-26_04 13 09](https://github.com/SmashingMods/Volcano-Block/assets/134662256/13e51566-a04b-4778-a1ca-bddf26019c42)
![2023-05-26_04 13 16](https://github.com/SmashingMods/Volcano-Block/assets/134662256/9dccc228-47e4-43ff-b22d-0cdbb3a67374)
![2023-05-26_04 13 21](https://github.com/SmashingMods/Volcano-Block/assets/134662256/27414d89-7a76-48ce-bd7a-10fde7659f76)

**Comment by MasterEnderman** [comment]
https://github.com/SmashingMods/Volcano-Block/issues/157
