### ISSUE TITLE
hostile neural network error

### ISSUE THREAD

**Issue by Fellal1** [SmashingMods/Volcano-Block#194]
![화면 캡처 2023-08-04 042451](https://github.com/SmashingMods/Volcano-Block/assets/83914598/647e16c1-c928-4ac0-95b6-363518a89dc8)
![화면 캡처 2023-08-04 042505](https://github.com/SmashingMods/Volcano-Block/assets/83914598/4de2048d-8b48-4bce-923d-5bb5acf47e93)
Piglich Data Model does not disappear. I update the game, turn it off, and turn it back on, but it not disappear

**Comment by MasterEnderman** [comment]
Wrong modpack: https://github.com/AllTheMods/VolcanoBlock/issues

**Comment by Fellal1** [comment]
oh sry
