### ISSUE TITLE
Smelting dust in modded furnace creates ic2 ingots

### ISSUE THREAD

**Issue by DeeDoubleYous** [SmashingMods/Volcano-Block#195]
When smelting silver in a redstone furnace and the electric furnaces creates the ic2 versions of the ingots rather than the alltheores version of the ingot. Tin becomes the ic2 version of the ingot in the electric furnace

**Comment by MasterEnderman** [comment]
Wrong modpack: https://github.com/AllTheMods/VolcanoBlock/issues
