### ISSUE TITLE
exit code 1

### ISSUE THREAD

**Issue by aXis-000** [SmashingMods/Volcano-Block#204]
When I start Volcano Block 1.1.9 and 1.1.8, after waiting for a few seconds I get an exit code 1 error and cannot start.
We have confirmed that it can be activated in 1.1.7.
(This text is using a translator)

**Comment by rozbrajaczpoziomow** [comment]
Please use https://mclo.gs/ to upload your latest.log and send the link it gives here.

**Comment by lightout11** [comment]
https://mclo.gs/4RZy109

**Comment by lightout11** [comment]
> Please use https://mclo.gs/ to upload your latest.log and send the link it gives here.

https://mclo.gs/4RZy109

**Comment by MasterEnderman** [comment]
Update SerilizationIsBad or remove the mod.
