### ISSUE TITLE
Sky is blue

### ISSUE THREAD

**Issue by ghost** [SmashingMods/Volcano-Block#207]
updated the pack to 1.1.10 and noticed the issue, removed the modpack and did a fresh install, default configs and sky is still blue

**Comment by MasterEnderman** [comment]
Not an issue.
I removed all mods that I previously used to tweak the skybox. Sadly these caused a few other issues and incompatibilities. Sadly there aren't any good mods that allow tweaking the skybox and the fog around the player. Until I figure something out and to keep the pack as stable as possible. That's how it stays.

**Comment by MasterEnderman** [comment]
Handled by #208
