### ISSUE TITLE
Pure Daisy only converts vertically placed Cherrywood Logs

### ISSUE THREAD

**Issue by Vhisarion** [SmashingMods/Volcano-Block#29]
As title says, pùre daisy only converts cherrywood logs when they're placed vertically, not when they're placed horizontally.

Not too much of a hassle, just little details.

**Comment by al132mc** [comment]
I'm aware of this, though I currently don't know how I can fix it...

**Comment by AuraChanneler** [comment]
> I'm aware of this, though I currently don't know how I can fix it...

I would think you need to find some way of making it ignore the NBT, perhaps? I don't know if vanilla botania has this same problem, though.
