### ISSUE TITLE
LAN issue

### ISSUE THREAD

**Issue by 630R63** [SmashingMods/Volcano-Block#38]
Whenever a friend joins my world via LAN, everything is dark, including my character. They are not able to see or interact with anything. They just keep falling in lava and burning to death.

**Comment by al132mc** [comment]
Yes, this is a known issue that people have trouble with LAN. Unsure how to fix unfortunately

**Comment by Mikse-jpg** [comment]
Have you found the problem yet?

**Comment by al132mc** [comment]
It is a bug with Topography, beyond my control

**Comment by Mikse-jpg** [comment]
Any other way I can play with my friend then?

**Comment by al132mc** [comment]
Explaining /how/ to do this is beyond the scope of the support I will provide you, but you could find a server to join or one of you could run a MinecraftForge server on one of your computers with the pack installed and then you should both be able to join it.

**Comment by Mikse-jpg** [comment]
Do you know a server where we can play it?

**Comment by al132mc** [comment]
I forgot to mention, if you would like your own private server I am partnered with [a server hosting company](https://www.akliz.net/al132) that has one-click installation for Volcano Block. Otherwise, we do currently have an official public server, join [our discord](https://discord.gg/4swu3fy
) for more info on that if you haven't already

**Comment by Mikse-jpg** [comment]
I used Akliz server, but it does not have volcano block 1.0.5. What can I do?

**Comment by al132mc** [comment]
They update their server packs ever Monday I believe, it should not be much trouble to re-install Volcano Block for whatever version Akliz is on for now, most updates only add a minimal amount of changes anyway

**Comment by Mikse-jpg** [comment]
Thank you! And I love this mod. You have done some great work.

**Comment by MattKaboom** [comment]
POSSIBLE LAN ISSUE WORKAROUND: I have disable topography and have installed spawn control (to remove mob spawning) and exact spawn, then i have make a superflat word with 1 layer of bedrock and 60 of lava. I have manually make a 7x7 platform of dirt and cobblestone like a original map than i have set the exact spawn. I have installed also stellar sky and set that for a end skybox because i cant find a nether skybox. All that can work or can make some problems?

**Comment by davethwave** [comment]
Best way to see which mod is responsible if any(could be some config or conflict thing) is to remove mod one by one and see if it runs good, however you need 2 computers to use this method unfortunately.

**Comment by al132mc** [comment]
We already know it's the mod topography, which is essential to the pack.  I reported the bug to the devs over 1.5 months ago, but it is what it is..

**Comment by LucasOnFire** [comment]
Alright so after experimenting with my friends we found an actual solution where you don't have to spend money to host a server. So the first thing you do is make sure who is going to host the server as everyone else is going to follow steps 4-7 and 10.
For the one hosting follow these steps:
1) Load up the modpack as normal.
2) Create the world (with cheats just in case)
3) Once the world is loaded exit the world and close the game.
4) Go into the modpack folder (if on curseforge right click the profile and click open folder)
5) Locate the mods folder.
6) Delete the topography mod (or move it elsewhere if you want to make a server yourself and can just put it back in).
7) Load up the modpack as normal.
8) Enter the world created in step 2.
9) Open to lan (you should know what to do from here but if you dont get radmin (blue shield icon) and have everyone join a server on there)
10)*For those who will join the person hosting: Copy the host's ip into the multiplayer tab, put a colon, and type in the port numbers that the host will see in his chat.

This should mostly work and should be done in a world with cheats on the chance that something doesn't work. This solution should work for most as all the topography mod is needed is to just load up the world that the author created and seems to not be needed afterwards and prohibits lan playing. This will slightly modify the world (no fog :O) but the game is still majorly playable. Hope this helps.

**Comment by OniyaMCD** [comment]
Have you checked to make sure that new terrain (that is, lava all the way to bedrock) generates properly if people move into new chunks?

**Comment by LucasOnFire** [comment]
Yes and I fixed my comment, the new terrain around actually loads in chunks of normal vanilla terrain but as long as enough chunks are loaded around it should be fine for a normal playthrough. Thank you for mentioning this.
