### ISSUE TITLE
Anima Core Broken Texture

### ISSUE THREAD

**Issue by defensiveSpirit** [SmashingMods/Volcano-Block#51]
I've noticed that after growing an anima core for leather, that a texture of it seems to have kept growing infinitely and expanding, not sure how badly it has affected my frame-rates, but it has certainly affected my frames decently
![Untitled](https://user-images.githubusercontent.com/51844187/60008969-a27ecf80-963a-11e9-9910-3987747ebe11.png)

**Comment by al132mc** [comment]
The mod author has been notified and I have disabled the inert seed recipes for now, but I will leave this issue open

**Comment by MasterEnderman** [comment]
Hearth Well won't get any updates for 1.12 so the anima core / inert seed stays disabled.
