### ISSUE TITLE
Straw Golem Blacklist

### ISSUE THREAD

**Issue by swoolcock** [SmashingMods/Volcano-Block#69]
Straw Golem now supports white/blacklist.  Could you please add some of the Unique Crops to the blacklist?  There are a handful that you would never want the golems to harvest.  Artisia and Cobblonia crops, for example.

I think these are the correct registry names:

```
S:filterMode=blacklist

S:blacklist <
    uniquecrops:cropartisia
    uniquecrops:cropcobblonia
>
```

**Comment by al132mc** [comment]
The blacklist doesn't seem to work, unfortunately

**Comment by swoolcock** [comment]
There's a bug which has since been fixed, just waiting on the Straw Golem to accept the pull request.

**Comment by loudwhitenoise** [comment]
I suggest adding instabilis to this list. If you aren't growing it with bonemeal but instead letting it grow on its own, the golems kill the patch by harvesting.

**Comment by MasterEnderman** [comment]
https://github.com/NivOridocs/strawgolem/pull/12

The pull request hasn't been merged. So I guess the mod is probably dead (for 1.12.2). I may fork it to publish a version with a working blacklist in the future.

**Comment by MasterEnderman** [comment]
Alright now I wait for curseforge to approve it so it can be included in the next update.
