### ISSUE TITLE
Infinite Sledgehammers (Soulus)

### ISSUE THREAD

**Issue by defensiveSpirit** [SmashingMods/Volcano-Block#85]
If you have 2 slightly damaged sledgehammers, and you combine them, you get infinite sledgehammers
![image](https://user-images.githubusercontent.com/51844187/61601893-1cd04e80-abfd-11e9-9829-b144019b1154.png)

**Comment by al132mc** [comment]
https://github.com/Yuudaari/soulus/issues/84
